# Generated by Django 5.0.1 on 2024-02-14 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='game',
            table='game',
        ),
        migrations.AlterModelTable(
            name='gameplayer',
            table='gameplayer',
        ),
    ]
