# Generated by Django 5.0.1 on 2024-02-14 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_game_table_alter_gameplayer_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gameplayer',
            table='game_player',
        ),
    ]
