# Generated by Django 5.0.2 on 2024-02-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_game_player1_game_player1_score_game_player2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='input_device',
            field=models.CharField(choices=[(0, 'KeyBoard'), (1, 'Mouse')], default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='game',
            name='mode',
            field=models.CharField(choices=[(0, 'Quick Match'), (1, 'Invite Friend')], default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='game',
            name='speed',
            field=models.CharField(choices=[(0, 'Easy'), (1, 'Normal'), (2, 'Hard')], default=1, max_length=1),
        ),
    ]
