# Generated by Django 5.0.1 on 2024-02-14 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='block',
            table='block',
        ),
        migrations.AlterModelTable(
            name='friend',
            table='friend',
        ),
        migrations.AlterModelTable(
            name='player',
            table='player',
        ),
    ]
