# Generated by Django 5.0.1 on 2024-02-14 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_alter_block_table_alter_friend_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='blocked_id',
            new_name='blocked',
        ),
        migrations.RenameField(
            model_name='block',
            old_name='blocker_id',
            new_name='blocker',
        ),
        migrations.RenameField(
            model_name='friend',
            old_name='followed_id',
            new_name='followed',
        ),
        migrations.RenameField(
            model_name='friend',
            old_name='follower_id',
            new_name='follower',
        ),
    ]
